sudo: required
services:
  - docker

before install:
  - docker build -t hsp8412/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hsp8412/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-027662361412"
  bucket_path: "frontend"
  on: branch:main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
